### ISSUE TITLE
Mohist world trouble

### ISSUE THREAD

**Issue by Mafy-17** [EricLangezaal/ZombieApocalypse#10]
ok so when I use plugin on paper (1.16.5) latest plugin vers it works fine it lists al worlds  e.g. world nether the_end  but in mohist it lists world  DIM1 and DIM-1  and it says world is not loaded/does not exist but DIM1 and DIM-1 work for nether and maybe end idk I didn't go there  I think the thing is that in mohist end and nether are within THE world folder so it makes trouble when trying to start apo on world as it can't tell if it is the world or an normal folder or smth
![image](https://user-images.githubusercontent.com/92233613/190876257-23a89d1a-1671-4152-b6ab-bd92c668b7f1.png)

**Comment by Mafy-17** [comment]
also may I suggest you make a discord for your plugins/support etc...

**Comment by EricLangezaal** [comment]
I responded in the Spigot thread already, but will respond here too more elaborately. The problem is indeed that Mohist works completely different from Spigot, so my plugin cannot find the world folders. There is a good chance that there is nothing I can do about this, since my plugin is made for Spigot/Paper and their forks, Mohist is not supported. The reason is that I cannot support Mohist since they decided to break so much, meaning my plugin would have to be modified extensively. And since Mohist is such a small platform comparatively, I can't budget in the time to do so. 
 
In the future I might look into ways to support both Spigot and Mohist's world handling system in the same plugin, but I don't think that is possible in a clean way.

**Comment by EricLangezaal** [comment]
> also may I suggest you make a discord for your plugins/support etc...

This has been suggested before. At this time I really don't see the benefit in it. I am the only author and person providing support for any of my plugins. Unlike some authors, I respond quickly on Spigot. I really like having all plugin related communication on Spigot, instead of having to set up an external platform (which takes time/effort) to effectively achieve the same. Especially the Spigot discussion thread already provides all functionality that a Discord would, since it is literally a channel/thread per plugin, where everyone can see each other's questions/answers.
