### ISSUE TITLE
Spawns a lot of zombies

### ISSUE THREAD

**Issue by Miner16** [EricLangezaal/ZombieApocalypse#11]
My players were just casually playing but then like 50+ zombies spawned NEXT to them. I assume it is cause the were all in the same place and the plugin had no other place to spawn the zombies. What is the fix (if any) for this problem

**Comment by EricLangezaal** [comment]
Well the thing is that my plugin does not modify the mob spawning algorithm at all. I replace vanilla monsters (skeletons, spiders, enderman etc etc) with zombies whenever they spawn. So unless you are using an outdated version of this plugin (or used custom zombie eggs/spawners), mob spawning will be **identical** to vanilla. So this is likely a Minecraft issue, not one caused by my plugin.
