### ISSUE TITLE
HOW DO I MAKE IT SO IT DOESNT OVERRIDE RAIDERS

### ISSUE THREAD

**Issue by Grandmaquil** [EricLangezaal/ZombieApocalypse#14]
when a raid starts zombies spawn and no raider

**Comment by EricLangezaal** [comment]
That's a good point actually, my plugin replaces all vanilla monsters to emulate a zombie apocalypse so it will indeed also replace raiders, which I realise might be undesired. 
If I have the time for it, I will release an update to fix this. Since this is a free plugin though, that might take a while.

**Comment by EricLangezaal** [comment]
This has been fixed in the latest update, any monsters that spawn with the spawnreason 'RAID' will be excluded from the apocalypse and not turned into zombies. If you like this update, be sure to leave a review;)

**Comment by Grandmaquil** [comment]
thanks man appriciate it
