### ISSUE TITLE
Problems headdrops

### ISSUE THREAD

**Issue by CloudeLecaw** [EricLangezaal/ZombieApocalypse#17]
We use a plugin called DropEdit

When this plugin is used it does not Drop Any Heads anymore as custom drops

When The plugin is unloadded then the heads drops aggain

We are using ZombieApocalypse_1.4.8  with Paper 1.20.1 (Build 196)

**Comment by EricLangezaal** [comment]
So just to clarify: when you use ZombieApocalypse, zombies will no longer drop custom heads? (Assuming it doesn't apply to other mobs). That is indeed to be expected, as my plugin automatically removes heads from dropping once a zombie dies, mostly to prevent those textures skulls from dropping, since that is not very vanilla-like. I can however imagine that there are cases where you would want to drop these skulls. If you want, I can make it configurable whether zombie apocalypse zombies can possibly drop their heads?

**Comment by CloudeLecaw** [comment]
an other developer allready told me that your plugin does this for all zombies..
He also wrote me a little fix with removing that part from the code.
![image](https://github.com/EricLangezaal/ZombieApocalypse/assets/12080017/b3a71e6d-e3c8-4ea4-9831-2e76697c5a84)


in our "fixed" version the problem is solved for us. but it would be nice for the others and for the officall version to also have a fix or alternative option.

An option would be nice maybe in config. So we could decide if we want that behave or not =)

**Comment by EricLangezaal** [comment]
> an other developer allready told me that your plugin does this for all zombies..

Haha yes I am aware, I made it like that on purpose:) The main reason is that I didn't want the plugin to drop the skulls by default, since in Vanilla mobs don't drop heads either (and the custom skulls were intended as a purely cosmetic thing). 
I am not going to remove it for that reason, but definitely agree that there should be a configuration option to switch it on or off. 

I have pushed an updated version to this repository, will upload a new version to Spigot if I have some more features or if more people run into this problem (too minor a change to warrant an update on its own).
