### ISSUE TITLE
[Feature Request] Towny Compatibility

### ISSUE THREAD

**Issue by Nobookie** [EricLangezaal/ZombieApocalypse#20]
Is there a way to make the plugin compatible with zombies?

It seems that zombies do not spawn in protected plots with "mob spawn: disabled". You could implement the Towny API and make zombies spawn in ongoing Apocalypses.

**Comment by EricLangezaal** [comment]
Yes my plugin is compatible with most other plugins that alter mob spawning already. Are you sure there aren't any typos in your previous message? Like surely you **don't** want any apocalypse zombies to spawn inside regions that have "mob spawn: disabled"? Apocalypse zombies are just regular monsters, so if you want them to spawn, just make sure you allow regular monsters to spawn.

My plugin listens to other plugins such a Towny/WorldGuard, such that if they block spawning my plugin will not spawn zombies either, since this is what 99% of the users of my plugin want haha.
