### ISSUE TITLE
Steve heads 

### ISSUE THREAD

**Issue by gunnar1997** [EricLangezaal/ZombieApocalypse#21]
the head data isn't coming though for some reason just steve heads for some reason.

on another note i found a plugin that caps spawn limites rather well for your plugin it is rather nice i thought i would let you know

EntityLimiter  by jukerx , on the modrinth website 
____________________________________________________________
setting for entitylimiter are : 

Radius to limit entities per radius of each entity.
Set Radius to 0 if you want it to count Globally (Even though minecraft worlds are flat)
Radius: 3.0
Height of the radius
HeightRadius: 1000.0
Limit entities per radius.
Limit: 5
----------------------------------------------------------------------------------
the height helps alot keeps them from spawning underground at night and the day is nicer too i was going from 10k plus entities at night too 3k at night huge performance boost overall

**Comment by gunnar1997** [comment]
![image](https://github.com/user-attachments/assets/f643306d-eeb0-4450-8f59-b14b44001620)

**Comment by EricLangezaal** [comment]
Thank you for letting me know here, I will have a look as to what has been changed that is causing zombie heads to break. Which Spigot version and plugin version are you on?

**Comment by gunnar1997** [comment]
I am running {paper mc} 1.21.1 and using the latest ZombieApocalypse Plugin 1.4.10 i tested this plugin on the lastest purpur and spigot both had the same issue unfortunately but i'm glad to say that was the only error other than that ZombieApocalypse works great!!

**Comment by EricLangezaal** [comment]
Fixed the custom zombie skulls in the new update, please do check it out and leave a review if you like it!:)

Thank you for the suggestion of the spawn limitting! Unfortunately the plugin you linked is quite poorly written (I had a look at its codebase), and will lead to a substantial negative impact to performance due to the way it tries to modify mob spawning. The main problem is that plugins (on Spigot, I believe Paper has better API here) cannot tell Minecraft where to spawn, they can only cancel spawns once Minecraft has already processed the whole entity. So by doing that repetitively like the plugin you linked does, Minecraft will then keep trying to spawn the mobs again every few ticks which keeps getting cancelled, which will hurt performance.

For that exact reason, ZombieApocalypse only had the option to modify the mobcap, which is a true Vanilla mechanism that does allow for very efficient (although rudimentary) control. However, due to popular demand, I added a setting you will probably like that allows you to specify the minimum height for an apocalypse zombie to spawn! It is much much more efficient than the spawn plugin linked, but it could still negatively impact performance. So I therefore won't likely add many settings like it
